name: Monopoly Tests
run-name: Build and Test
on: [push]
jobs:
  build:
    name: Setup
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: seanmiddleditch/gha-setup-ninja@master
      - run: mkdir build & cd build & cmake -G Ninja .
      - run: cmake --build build
      
