name: Monopoly Tests
run-name: Build and Test
on: [push]
jobs:
  build:
    name: Setup
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: seanmiddleditch/gha-setup-ninja@master
        
      - name: Build
        run: |
            mkdir build
              cd build
              cmake -G Ninja ..

      - name: Move files to build directory
        run: cmake --build build

  tests:
    needs: [build]
    name: Tests
    runs-on: ubuntu-latest
    steps: 
      - name: Run tests
        run: ctest --test-dir MonopolyTests --output-junit build/test-results/test/TEST-slot.xml

      - name: Publish Test Report
        uses: mikepenz/action-junit-report@v5
        if: success() || failure() # always run even if the previous step fails
        with:
          report_paths: '**/build/test-results/test/TEST-*.xml'
      
